#ifndef _TOPICIDS_H
#define _TOPICIDS_H

// YOU MUST KEEP THIS VARIABLE UP TO DATE !!!!

#define NUM_TOPIC_IDS               23

/* #define TOPIC_MEMORY_MANAGER        0
#define TOPIC_FILE_MANAGER          1
#define TOPIC_DATABASE_MANAGER      2
#define TOPIC_GAME                  3
#define TOPIC_SGP                   4
#define TOPIC_VIDEO                 5
#define TOPIC_INPUT                 6
#define TOPIC_STACK_CONTAINERS      7
#define TOPIC_LIST_CONTAINERS       8
#define TOPIC_QUEUE_CONTAINERS      9
#define TOPIC_PRILIST_CONTAINERS    10
#define TOPIC_HIMAGE                11
#define TOPIC_ORDLIST_CONTAINERS		12
#define TOPIC_3DENGINE              13
#define TOPIC_VIDEOOBJECT           14
#define TOPIC_FONT_HANDLER          15
#define TOPIC_VIDEOSURFACE          16
#define TOPIC_MOUSE_SYSTEM          17
#define TOPIC_BUTTON_HANDLER        18
#define TOPIC_MUTEX                 19
#define TOPIC_JA2										20
#define TOPIC_BLIT_QUEUE						21
#define TOPIC_JA2OPPLIST						22
*/

#ifdef __cplusplus
extern "C" {
#endif

extern UINT16 TOPIC_MEMORY_MANAGER;
extern UINT16 TOPIC_FILE_MANAGER;
extern UINT16 TOPIC_DATABASE_MANAGER;
extern UINT16 TOPIC_GAME;
extern UINT16 TOPIC_SGP;
extern UINT16 TOPIC_VIDEO;
extern UINT16 TOPIC_INPUT;
extern UINT16 TOPIC_STACK_CONTAINERS;
extern UINT16 TOPIC_LIST_CONTAINERS;
extern UINT16 TOPIC_QUEUE_CONTAINERS;
extern UINT16 TOPIC_PRILIST_CONTAINERS;
extern UINT16 TOPIC_HIMAGE;
extern UINT16 TOPIC_ORDLIST_CONTAINERS;
extern UINT16 TOPIC_3DENGINE;
extern UINT16 TOPIC_VIDEOOBJECT;
extern UINT16 TOPIC_FONT_HANDLER;
extern UINT16 TOPIC_VIDEOSURFACE;
extern UINT16 TOPIC_MOUSE_SYSTEM;
extern UINT16 TOPIC_BUTTON_HANDLER;
extern UINT16 TOPIC_MUTEX;
extern UINT16 TOPIC_JA2;
extern UINT16 TOPIC_BLIT_QUEUE;
extern UINT16 TOPIC_JA2OPPLIST;
extern UINT16 TOPIC_JA2AI;

#ifdef __cplusplus
}
#endif

#endif	// NUM_TOPICS_IDS
