# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "tmatilai/openbsd-5.5"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "strac_buildbox_openbsd-5.5"
    vb.cpus = 2
  #   vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

end
