VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "kaorimatz/openbsd-5.9-amd64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../..", "/home/vagrant/strac", id: "vagrant-root", :nfs => true
  config.ssh.shell = "sh"
  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.provision :shell, :path => "./bootstrap.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.check_guest_additions = false
    vb.functional_vboxsf = false

    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.define "openbsd" do |openbsd|
  end
end
