#pragma once

#include "RustInterface.h"

#define NUMBER_OF_TOPICS  63
#define TAG_LENGTH        15

typedef enum
{
  DEBUG_TAG_GAMELOOP, // 0
  DEBUG_TAG_SMAP,
  DEBUG_TAG_AI,
  DEBUG_TAG_SCHEDULER,
  DEBUG_TAG_PATHAI,
  DEBUG_TAG_ANIMATIONS, // 5
  DEBUG_TAG_GAP,
  DEBUG_TAG_WEAPONS,
  DEBUG_TAG_OVERHEAD,
  DEBUG_TAG_KEYS,
  DEBUG_TAG_POINTS, // 10
  DEBUG_TAG_MORALE,
  DEBUG_TAG_MERCHIRE,
  DEBUG_TAG_OPPLIST,
  DEBUG_TAG_LIGHTING,
  DEBUG_TAG_RENDERWORLD, // 15
  DEBUG_TAG_TILES,
  DEBUG_TAG_EXPLOSION,
  DEBUG_TAG_PHYSICS,
  DEBUG_TAG_AMBIENT,
  DEBUG_TAG_SAVELOAD, // 20
  DEBUG_TAG_MUSICCTL,
  DEBUG_TAG_SMK,
  DEBUG_TAG_EVENTPUMP,
  DEBUG_TAG_QUESTS,
  DEBUG_TAG_EDITOR, // 25
  DEBUG_TAG_RESOURCES,
  DEBUG_TAG_JA2SCREENS,
  DEBUG_TAG_INIT,
  DEBUG_TAG_FONT,
  DEBUG_TAG_SGP, // 30
  DEBUG_TAG_STCI,
  DEBUG_TAG_CONTAINER,
  DEBUG_TAG_VIDEO,
  DEBUG_TAG_VSURFACE,
  DEBUG_TAG_SOUND, // 35
  DEBUG_TAG_MEMORY,
  DEBUG_TAG_GAMESCREEN,
  DEBUG_TAG_BOBBYRAY,
  DEBUG_TAG_SAI,
  DEBUG_TAG_AIRRAID, // 40
  DEBUG_TAG_BULLETS,
  DEBUG_TAG_HANDLEITEMS,
  DEBUG_TAG_INTERFACE,
  DEBUG_TAG_LOS,
  DEBUG_TAG_TACTSAVE, // 45
  DEBUG_TAG_TEAMTURN,
  DEBUG_TAG_WORLDDEF,
  DEBUG_TAG_HIMAGE,
  DEBUG_TAG_LIBDB,
  DEBUG_TAG_FILEMAN, // 50
  DEBUG_TAG_MODPACK,
  DEBUG_TAG_DEFAULTCM,
  DEBUG_TAG_SOLDIER,
  DEBUG_TAG_ASSERTS,
  DEBUG_TAG_QUEENCMD, // 55
  DEBUG_TAG_NPC,
  DEBUG_TAG_CAMPAIGN,
  DEBUG_TAG_LOYALTY,
  DEBUG_TAG_AUTORESOLVE,
  DEBUG_TAG_CORPSES, // 60
  DEBUG_TAG_FIXME,
  DEBUG_TAG_LAUNCHER
}
SLOGTopics;

void LogMessage(LogLevel level, SLOGTopics topic, const char *format, ...);

/** Print debug message macro. */
#define SLOGD(TAG, FORMAT, ...) LogMessage(LogLevel::Debug, TAG, FORMAT, ##__VA_ARGS__)

/** Print info message macro. */
#define SLOGI(TAG, FORMAT, ...) LogMessage(LogLevel::Info,  TAG, FORMAT, ##__VA_ARGS__)

/** Print warning message macro. */
#define SLOGW(TAG, FORMAT, ...) LogMessage(LogLevel::Warn, TAG, FORMAT, ##__VA_ARGS__)

/** Print error message macro. */
#define SLOGE(TAG, FORMAT, ...) LogMessage(LogLevel::Error, TAG, FORMAT, ##__VA_ARGS__)