#ifndef TOPICIDS_H
#define TOPICIDS_H

enum TopicID
{
	TOPIC_MEMORY_MANAGER,
	TOPIC_GAME,
	TOPIC_VIDEO,
	TOPIC_LIST_CONTAINERS,
	TOPIC_QUEUE_CONTAINERS,
	TOPIC_HIMAGE,
	TOPIC_VIDEOOBJECT,
	TOPIC_FONT_HANDLER,
	TOPIC_VIDEOSURFACE,
	TOPIC_MOUSE_SYSTEM,
	TOPIC_BUTTON_HANDLER,
	TOPIC_JA2,
	TOPIC_JA2OPPLIST,
	TOPIC_JA2AI,
	TOPIC_JA2SAI,
	TOPIC_JA2EDITOR
};

#endif
