# -*- mode: ruby -*-
# vi: set ft=ruby :

# This box is for buidling:
#   1) windows release

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise64"

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.synced_folder "../../..", "/home/vagrant/strac"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "strac_buildbox_u1204_amd64_win"
    vb.cpus = 2
  #   vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

end
