// Profiles written by the 0.21 releases (648 byte record). The same fields as
// later layouts, in an older order: the palette strings came right after the
// face index, ahead of the character's own particulars. No voice field; like
// 0.22 it kept the voice in ubSuspiciousDeath (see v022.ts).

import type { FieldDef } from "../binary/layout.ts";
import type { Profile } from "../model/profile.ts";
import { binaryImporter } from "./binary.ts";

const PLAYER_GENERATED_CHARACTER_ID = 51;

// ProfileV21 in #2523's IMPProfileMigration.cc.
const FIELDS: readonly FieldDef[] = [
	["zName", "string"],
	["zNickname", "string"],
	["ubFaceIndex", "u8"],
	["PANTS", "string"],
	["VEST", "string"],
	["SKIN", "string"],
	["HAIR", "string"],
	["bSex", "i8"],
	["bArmourAttractiveness", "i8"],
	["ubMiscFlags2", "u8"],
	["bEvolution", "i8"],
	["ubMiscFlags", "u8"],
	["bSexist", "u8"],
	["bLearnToHate", "i8"],
	["ubQuoteRecord", "u8"],
	["bDeathRate", "i8"],
	["sExpLevelGain", "i16"],
	["sLifeGain", "i16"],
	["sAgilityGain", "i16"],
	["sDexterityGain", "i16"],
	["sWisdomGain", "i16"],
	["sMarksmanshipGain", "i16"],
	["sMedicalGain", "i16"],
	["sMechanicGain", "i16"],
	["sExplosivesGain", "i16"],
	["ubBodyType", "u8"],
	["bMedical", "i8"],
	["usEyesX", "u16"],
	["usEyesY", "u16"],
	["usMouthX", "u16"],
	["usMouthY", "u16"],
	["uiBlinkFrequency", "u32"],
	["uiExpressionFrequency", "u32"],
	["sSector", "sector"],
	["uiDayBecomesAvailable", "u32"],
	["bStrength", "i8"],
	["bLifeMax", "i8"],
	["bExpLevelDelta", "i8"],
	["bLifeDelta", "i8"],
	["bAgilityDelta", "i8"],
	["bDexterityDelta", "i8"],
	["bWisdomDelta", "i8"],
	["bMarksmanshipDelta", "i8"],
	["bMedicalDelta", "i8"],
	["bMechanicDelta", "i8"],
	["bExplosivesDelta", "i8"],
	["bStrengthDelta", "i8"],
	["bLeadershipDelta", "i8"],
	["usKills", "u16"],
	["usAssists", "u16"],
	["usShotsFired", "u16"],
	["usShotsHit", "u16"],
	["usBattlesFought", "u16"],
	["usTimesWounded", "u16"],
	["usTotalDaysServed", "u16"],
	["sLeadershipGain", "i16"],
	["sStrengthGain", "i16"],
	["uiBodyTypeSubFlags", "u32"],
	["sSalary", "i16"],
	["bLife", "i8"],
	["bDexterity", "i8"],
	["bPersonalityTrait", "i8"],
	["bSkillTrait", "i8"],
	["bReputationTolerance", "i8"],
	["bExplosive", "i8"],
	["bSkillTrait2", "i8"],
	["bLeadership", "i8"],
	["bBuddy", "i8", [5]],
	["bHated", "i8", [5]],
	["bExpLevel", "i8"],
	["bMarksmanship", "i8"],
	["bWisdom", "i8"],
	["bInvStatus", "u8", [19]],
	["bInvNumber", "u8", [19]],
	["usApproachFactor", "u16", [4]],
	["bMainGunAttractiveness", "i8"],
	["bAgility", "i8"],
	["fUseProfileInsertionInfo", "bool"],
	["sGridNo", "i16"],
	["ubQuoteActionID", "u8"],
	["bMechanical", "i8"],
	["ubInvUndroppable", "u8"],
	["ubRoomRangeStart", "u8", [2]],
	["inv", "u16", [19]],
	["usStatChangeChances", "u16", [12]],
	["usStatChangeSuccesses", "u16", [12]],
	["ubStrategicInsertionCode", "u8"],
	["ubRoomRangeEnd", "u8", [2]],
	["ubLastQuoteSaid", "u8"],
	["bRace", "i8"],
	["bNationality", "i8"],
	["bAppearance", "i8"],
	["bAppearanceCareLevel", "i8"],
	["bRefinement", "i8"],
	["bRefinementCareLevel", "i8"],
	["bHatedNationality", "i8"],
	["bHatedNationalityCareLevel", "i8"],
	["bRacist", "i8"],
	["uiWeeklySalary", "u32"],
	["uiBiWeeklySalary", "u32"],
	["bMedicalDeposit", "i8"],
	["bAttitude", "i8"],
	["sMedicalDepositAmount", "u16"],
	["bLearnToLike", "i8"],
	["ubApproachVal", "u8", [4]],
	["ubApproachMod", "u8", [3, 4]],
	["bTown", "i8"],
	["bTownAttachment", "i8"],
	["usOptionalGearCost", "u16"],
	["bMercOpinion", "i8", [75]],
	["bApproached", "i8"],
	["bMercStatus", "i8"],
	["bHatedTime", "i8", [5]],
	["bLearnToLikeTime", "i8"],
	["bLearnToHateTime", "i8"],
	["bHatedCount", "i8", [5]],
	["bLearnToLikeCount", "i8"],
	["bLearnToHateCount", "i8"],
	["ubLastDateSpokenTo", "u8"],
	["bLastQuoteSaidWasSpecial", "u8"],
	["bSectorZ", "i8"],
	["usStrategicInsertionData", "u16"],
	["bFriendlyOrDirectDefaultResponseUsedRecently", "i8"],
	["bRecruitDefaultResponseUsedRecently", "i8"],
	["bThreatenDefaultResponseUsedRecently", "i8"],
	["bNPCData", "i8"],
	["iBalance", "i32"],
	["ubCivilianGroup", "u8"],
	["ubNeedForSleep", "u8"],
	["uiMoney", "u32"],
	["bNPCData2", "i8"],
	["ubMiscFlags3", "u8"],
	["ubDaysOfMoraleHangover", "u8"],
	["ubNumTimesDrugUseInLifetime", "u8"],
	["uiPrecedentQuoteSaid", "u32"],
	["sPreCombatGridNo", "i16"],
	["ubTimeTillNextHatedComplaint", "u8"],
	["ubSuspiciousDeath", "u8"],
	["iMercMercContractLength", "i32"],
	["uiTotalCostToDate", "u32"],
];

const spec = {
	id: "0.21",
	label: "0.21 binary",
	fields: FIELDS,
	voice: (p: Profile) => PLAYER_GENERATED_CHARACTER_ID + (p.ubSuspiciousDeath as number),
};

export const v021 = binaryImporter(spec);
export const v021x32 = binaryImporter({ ...spec, bits: 32 });
