// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "StracciatellaLauncher.h"

StracciatellaLauncher::StracciatellaLauncher() {
  { stracciatellaLauncher = new Fl_Double_Window(455, 290, "JA2 Stracciatella Launcher");
    stracciatellaLauncher->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(-1, 0, 456, 290);
      { Fl_Group* o = new Fl_Group(5, 10, 440, 65);
        o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        { dataDirectoryInput = new Fl_Input(145, 10, 270, 25, "Ja2 Data Directory:");
          dataDirectoryInput->align(Fl_Align(132));
        } // Fl_Input* dataDirectoryInput
        { gameVersionInput = new Fl_Input_Choice(145, 47, 300, 25, "Game Version:");
        } // Fl_Input_Choice* gameVersionInput
        { browseJa2DirectoryButton = new Fl_Button(420, 10, 25, 25, "...");
        } // Fl_Button* browseJa2DirectoryButton
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 105, 250, 175);
        { fullscreenCheckbox = new Fl_Check_Button(20, 232, 100, 20, "Fullscreen");
          fullscreenCheckbox->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* fullscreenCheckbox
        { Fl_Group* o = new Fl_Group(10, 105, 240, 120, "Resolution");
          o->box(FL_THIN_DOWN_FRAME);
          o->labelfont(1);
          { predefinedResolutionButton = new Fl_Round_Button(20, 115, 100, 20, "Predefined:");
            predefinedResolutionButton->down_box(FL_ROUND_DOWN_BOX);
          } // Fl_Round_Button* predefinedResolutionButton
          { customResolutionButton = new Fl_Round_Button(20, 165, 80, 20, "Custom:");
            customResolutionButton->down_box(FL_ROUND_DOWN_BOX);
          } // Fl_Round_Button* customResolutionButton
          { predefinedResolutionInput = new Fl_Input_Choice(40, 135, 180, 25);
          } // Fl_Input_Choice* predefinedResolutionInput
          { customResolutionXInput = new Fl_Value_Input(40, 185, 80, 25);
            customResolutionXInput->minimum(640);
            customResolutionXInput->maximum(0);
            customResolutionXInput->value(640);
          } // Fl_Value_Input* customResolutionXInput
          { customResolutionYInput = new Fl_Value_Input(140, 185, 80, 25);
            customResolutionYInput->minimum(480);
            customResolutionYInput->maximum(0);
            customResolutionYInput->value(480);
          } // Fl_Value_Input* customResolutionYInput
          { new Fl_Box(120, 185, 20, 25, "x");
          } // Fl_Box* o
          o->end();
        } // Fl_Group* o
        { playSoundsCheckbox = new Fl_Check_Button(20, 252, 130, 19, "Play Sounds");
          playSoundsCheckbox->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* playSoundsCheckbox
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(260, 105, 185, 175);
        { playButton = new Fl_Button(260, 225, 185, 55, "Play Ja2 Stracciatella");
        } // Fl_Button* playButton
        { editorButton = new Fl_Button(260, 190, 185, 25, "Start Map Editor");
        } // Fl_Button* editorButton
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Group* o
    stracciatellaLauncher->end();
  } // Fl_Double_Window* stracciatellaLauncher
}
