build:
	gcc -o example01 -Wall example01.c   ../slog/slog.c -I..
	g++ -o example02 -Wall example02.cpp ../slog/slog.c -I..

clean:
	-rm example01 example01.exe example01-log.txt
	-rm example02 example02.exe example02-log.txt
