// The fields of MERCPROFILESTRUCT, in the order and with the C types a 64-bit
// build laid them out in at save version 104, the last layout written as a raw
// copy. The JSON format (version 1) has one key for each of them, under the
// same name. impSlotState is left out: it says whether a slot is taken in the
// game that wrote the file, and the JSON format does not carry it.
//
// Older layouts are this list with fields taken out; see src/importers/.

import type { FieldDef } from "../binary/layout.ts";

export const PROFILE_FIELDS: readonly FieldDef[] = [
	["zName", "string"],
	["zNickname", "string"],
	["bSex", "i8"],
	["ubCivilianGroup", "u8"],
	["ubMiscFlags", "u8"],
	["ubMiscFlags2", "u8"],
	["ubMiscFlags3", "u8"],
	["ubBodyType", "u8"],
	["uiBodyTypeSubFlags", "u32"],
	["ubFaceIndex", "u8"],
	["usEyesX", "u16"],
	["usEyesY", "u16"],
	["usMouthX", "u16"],
	["usMouthY", "u16"],
	["uiBlinkFrequency", "u32"],
	["uiExpressionFrequency", "u32"],
	["ubVoiceId", "u8"],
	["impSlotState", "u8"],
	["PANTS", "string"],
	["VEST", "string"],
	["SKIN", "string"],
	["HAIR", "string"],
	["bEvolution", "i8"],
	["bLifeMax", "i8"],
	["bLife", "i8"],
	["bAgility", "i8"],
	["bDexterity", "i8"],
	["bStrength", "i8"],
	["bLeadership", "i8"],
	["bWisdom", "i8"],
	["bExpLevel", "i8"],
	["bMarksmanship", "i8"],
	["bExplosive", "i8"],
	["bMechanical", "i8"],
	["bMedical", "i8"],
	["ubNeedForSleep", "u8"],
	["sLifeGain", "i16"],
	["bLifeDelta", "i8"],
	["sAgilityGain", "i16"],
	["bAgilityDelta", "i8"],
	["sDexterityGain", "i16"],
	["bDexterityDelta", "i8"],
	["sStrengthGain", "i16"],
	["bStrengthDelta", "i8"],
	["sLeadershipGain", "i16"],
	["bLeadershipDelta", "i8"],
	["sWisdomGain", "i16"],
	["bWisdomDelta", "i8"],
	["sExpLevelGain", "i16"],
	["bExpLevelDelta", "i8"],
	["sMarksmanshipGain", "i16"],
	["bMarksmanshipDelta", "i8"],
	["sExplosivesGain", "i16"],
	["bExplosivesDelta", "i8"],
	["sMechanicGain", "i16"],
	["bMechanicDelta", "i8"],
	["sMedicalGain", "i16"],
	["bMedicalDelta", "i8"],
	["usStatChangeChances", "u16", [12]],
	["usStatChangeSuccesses", "u16", [12]],
	["bPersonalityTrait", "i8"],
	["bSkillTrait", "i8"],
	["bSkillTrait2", "i8"],
	["bAttitude", "i8"],
	["bSexist", "u8"],
	["bMercStatus", "i8"],
	["bReputationTolerance", "i8"],
	["bDeathRate", "i8"],
	["uiDayBecomesAvailable", "u32"],
	["sSalary", "i16"],
	["uiWeeklySalary", "u32"],
	["uiBiWeeklySalary", "u32"],
	["bMedicalDeposit", "i8"],
	["sMedicalDepositAmount", "u16"],
	["iMercMercContractLength", "i32"],
	["usOptionalGearCost", "u16"],
	["ubSuspiciousDeath", "u8"],
	["ubDaysOfMoraleHangover", "u8"],
	["sSector", "sector"],
	["sGridNo", "i16"],
	["sPreCombatGridNo", "i16"],
	["ubStrategicInsertionCode", "u8"],
	["usStrategicInsertionData", "u16"],
	["fUseProfileInsertionInfo", "bool"],
	["bTown", "i8"],
	["bTownAttachment", "i8"],
	["ubRoomRangeStart", "u8", [2]],
	["ubRoomRangeEnd", "u8", [2]],
	["bBuddy", "i8", [5]],
	["bHated", "i8", [5]],
	["bHatedCount", "i8", [5]],
	["bHatedTime", "i8", [5]],
	["bLearnToLike", "i8"],
	["bLearnToLikeCount", "i8"],
	["bLearnToLikeTime", "i8"],
	["bLearnToHate", "i8"],
	["bLearnToHateCount", "i8"],
	["bLearnToHateTime", "i8"],
	["ubTimeTillNextHatedComplaint", "u8"],
	["bMercOpinion", "i8", [75]],
	["inv", "u16", [19]],
	["bInvNumber", "u8", [19]],
	["bInvStatus", "u8", [19]],
	["ubInvUndroppable", "u8"],
	["uiMoney", "u32"],
	["bArmourAttractiveness", "i8"],
	["bMainGunAttractiveness", "i8"],
	["iBalance", "i32"],
	["ubNumTimesDrugUseInLifetime", "u8"],
	["bNPCData", "i8"],
	["bNPCData2", "i8"],
	["ubQuoteRecord", "u8"],
	["ubLastQuoteSaid", "u8"],
	["uiPrecedentQuoteSaid", "u32"],
	["bLastQuoteSaidWasSpecial", "u8"],
	["ubLastDateSpokenTo", "u8"],
	["ubQuoteActionID", "u8"],
	["bFriendlyOrDirectDefaultResponseUsedRecently", "i8"],
	["bRecruitDefaultResponseUsedRecently", "i8"],
	["bThreatenDefaultResponseUsedRecently", "i8"],
	["bApproached", "i8"],
	["usApproachFactor", "u16", [4]],
	["ubApproachVal", "u8", [4]],
	["ubApproachMod", "u8", [3, 4]],
	["usKills", "u16"],
	["usAssists", "u16"],
	["usShotsFired", "u16"],
	["usShotsHit", "u16"],
	["usBattlesFought", "u16"],
	["usTimesWounded", "u16"],
	["usTotalDaysServed", "u16"],
	["uiTotalCostToDate", "u32"],
	["bSectorZ", "i8"],
	["bRace", "i8"],
	["bRacist", "i8"],
	["bNationality", "i8"],
	["bAppearance", "i8"],
	["bAppearanceCareLevel", "i8"],
	["bRefinement", "i8"],
	["bRefinementCareLevel", "i8"],
	["bHatedNationality", "i8"],
	["bHatedNationalityCareLevel", "i8"],
];

/** Fields that are part of the record but not of the JSON format. */
export const NOT_IN_JSON = new Set(["impSlotState"]);
