# -*- mode: ruby -*-
# vi: set ft=ruby :

# This box is for buidling:
#   1) i368 debian package

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.provision :shell, :path => "../common/ubuntu-bootstrap.sh"

  config.vm.synced_folder "../../..", "/home/vagrant/strac"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
  #   vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define "i386" do |i386|
  end

end
