# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :path => "../common/ubuntu-bootstrap.sh"

  config.vm.synced_folder "../../..", "/home/vagrant/strac"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
  #   vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.define "amd64" do |amd64|
  end

  config.vm.define "win" do |win|
  end

end
