#pragma once

enum MusicMode {
	MUSIC_NONE,
	MUSIC_RESTORE,
	MUSIC_MAIN_MENU,
	MUSIC_TACTICAL_NOTHING,
	MUSIC_TACTICAL_ENEMYPRESENT,
	MUSIC_TACTICAL_BATTLE,
	MUSIC_TACTICAL_VICTORY,
	MUSIC_TACTICAL_DEFEAT,
	MUSIC_LAPTOP,
	MUSIC_TACTICAL_CREATURE_NOTHING,
	MUSIC_TACTICAL_CREATURE_ENEMYPRESENT,
	MUSIC_TACTICAL_CREATURE_BATTLE,
	MAX_MUSIC_MODES
};
