.\" Manpage for ja2.
.\" Goto https://github.com/ja2-stracciatella/ja2-stracciatella to report or correct errors or typos.
.TH ja2 6 "30 November 2017" "1.0" "ja2 man page"
.SH NAME
ja2 \- JA2 Stracciatella
.SH SYNOPSIS
ja2 [OPTIONS]
.SH DESCRIPTION
JA2 Stracciatella is a cross-platform implementation of Jagged Alliance 2 game.
This is only the game engine.  Game resources from the original JA2 are required to play the game.
.TP
When you first start the game, file \fB~/.ja2/ja2.json\fR is created.  You should edit this file, so that \fBgame_dir\fR points to the directory of the original JA2 game.
.TP
You can also use ja2-launcher to comfortably configure the game.
.SH OPTIONS
.TP
\fB\-gamedir /opt/ja2\fR
Path to the original JA2 game
.TP
\fB\-res WxH\fR
Screen resolution, e.g. 800x600. Default value is 640x480
.TP
\fB\-brightness GAMMA\fR
Screen brightness (gamma multiplier) value to set where 0.0 is completely dark and 1.0 is normal brightness. Set to a negative value to disable brightness adjustment. Default value is -1
.br
NOTE: some video drivers do not support setting the gamma value and this option may not have any effect in those cases
.TP
\fB\-resversion VERSION\fR
Version of the game resources.
Possible values are: DUTCH, ENGLISH, FRENCH, GERMAN, ITALIAN, POLISH, RUSSIAN, RUSSIAN_GOLD.
Default value is ENGLISH.
Use RUSSIAN for the "BUKA Agonia Vlasty" release.
Use RUSSIAN_GOLD for the Russian Gold release.

.TP
\fB\-mod NAME\fR
Start one of the game modifications, bundled into the game.
NAME is the name of modification, e.g. 'from-russia-with-love'. See folder mods for possible options
.TP
\fB\-debug\fR
Show debug messages
.TP
\fB\-unittests\fR
Perform unit tests.
ja2 -unittests [gtest options]
E.g. ja2 -unittests --gtest_output="xml:report.xml" --gtest_repeat=2
.TP
\fB\-editor\fR
Start the map editor (Editor.slf is necessary)
.TP
\fB\-fullscreen\fR
Start the game in the fullscreen mode
.TP
\fB\-help\fR
Display this information
.TP
\fB\-nosound\fR
Turn the sound and music off
.TP
\fB\-window\fR
Start the game in a window
.SH AUTHOR
The JA2 Stracciatella Team
