find_path(
  UTF8CPP_INCLUDE_DIRS
  NAMES utf8.h
  PATHS ${CMAKE_INSTALL_PREFIX}/dependencies-root/include/utf8cpp
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LocalUtf8Cpp REQUIRED_VARS UTF8CPP_INCLUDE_DIRS)