set(SMACKER_INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/dependencies-root/include/libsmacker)

find_library(
    SMACKER_LIBRARIES
    NAMES smacker
    PATH_SUFFIXES lib lib64
    PATHS ${CMAKE_INSTALL_PREFIX}/dependencies-root
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Smacker REQUIRED_VARS SMACKER_LIBRARIES SMACKER_INCLUDE_DIRS)