find_library(
    STRACCIATELLA_LIBRARY
    NAMES stracciatella
    PATHS ${CMAKE_INSTALL_PREFIX}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Stracciatella REQUIRED_VARS STRACCIATELLA_LIBRARY)