set(LOCAL_GTEST_LIB OFF CACHE BOOL "" FORCE)

set(OPENBSD_FEATURE_TEST_MACROS "-D_POSIX_C_SOURCE=200809L -D_BSD_SOURCE")
set(CMAKE_CXX_FLAGS ${OPENBSD_FEATURE_TEST_MACROS})
set(CMAKE_C_FLAGS ${OPENBSD_FEATURE_TEST_MACROS})
