SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(LOCAL_SDL_LIB "_build/lib-SDL-devel-1.2.15-VC" CACHE STRING "" FORCE)
SET(LOCAL_BOOST_LIB ON CACHE BOOL "" FORCE)
SET(gtest_force_shared_crt ON CACHE BOOL "" FORCE)

ADD_DEFINITIONS("-DBOOST_ALL_NO_LIB")
