#pragma once

#include "Types.h"

#define INSURANCE_TEXT_SINGLE		1
#define INSURANCE_TEXT_MULTI		2

//Single line
enum
{
	INS_SNGL_MALLEUS_INCUS_STAPES,
	INS_SNGL_WERE_LISTENING,
	INS_SNGL_LIFE_INSURANCE_SPECIALISTS,
	INS_SNGL_COMMENTSFROM_CLIENTS,
	INS_SNGL_HOW_DOES_INS_WORK,
	INS_SNGL_TO_ENTER_REVIEW,
	INS_SNGL_GUS_TARBALLS,
	INS_SNGL_ALI_HUSSEAN,
	INS_SNGL_LANCE_ALLOT,
	INS_SNGL_FRED_COUSTEAU,
	INS_SNGL_WE_CAN_OFFER_U,
	INS_SNGL_PREMIUMS,
	INS_SNGL_RENEWL_PREMIUMS,
	INS_SNGL_LOWER_PREMIUMS_4_RENEWING,
	INS_SNGL_POLICY_CANCELATIONS,
	INS_SNGL_SUBMITTING_CLAIM,
	INS_SNGL_FRAUD,
	INS_SNGL_ENTERING_REVIEWING_CLAIM,
	INS_SNGL_EMPLOYMENT_CONTRACT,
	INS_SNGL_LENGTH,
	INS_SNGL_DAYS_REMAINING,
	INS_SNGL_INSURANCE_CONTRACT,
	INS_SNGL_PREMIUM_OWING,
	INS_SNGL_PREMIUM_REFUND,
	INS_SNGL_CHANGE_LENGTH,
	INS_SNGL_CONTRACT,
	INS_SNGL_NOCONTRACT,
	INS_SNGL_DEAD_WITH_CONTRACT,
	INS_SNGL_DEAD_NO_CONTRACT,
	INS_SNGL_PARTIALLY_INSURED,


	//Multi line
	INS_MULTI_LINE_BEGINS,


	INS_MLTI_EMPLOY_HIGH_RISK,
	INS_MLTI_HIGH_FATALITY_RATE,
	INS_MLTI_DRAIN_SALARY,
	INS_MLTI_IF_ANSWERED_YES,
	INS_MLTI_GUS_SPEECH,
	INS_MLTI_ALI_HUSSEAN_SPEECH,
	INS_MLTI_LANCE_ALLOT_SPEECH,
	INS_MLTI_FRED_COUSTEAU_SPEECH,
	INS_MLTI_HIRING_4_SHORT_TERM_HIGH_RISK_1,
	INS_MLTI_HIRING_4_SHORT_TERM_HIGH_RISK_2,
	INS_MLTI_REASONABLE_AND_FLEXIBLE,
	INS_MLTI_EQUITABLE_RENEWL_PREMIUMS,
	INS_MLTI_PREROGATIVE_TO_CANCEL,
	INS_MLTI_QUICKLY_AND_EFFICIENT,
	INS_MLTI_EACH_TIME_U_COME_TO_US,
	INS_MLTI_LENGTH_OF_EMPLOYMENT_CONTRACT,
	INS_MLTI_EMPLOYEES_AGE_AND_HEALTH,
	INS_MLTI_EMPLOOYEES_TRAINING_AND_EXP,
	INS_MLTI_WHEN_IT_COMES_TIME_TO_RENEW,
	INS_MLTI_SHOULD_THE_PROJECT_BE_GOING_WELL,
	INS_MLTI_IF_U_EXTEND_THE_CONTRACT,
	INS_MLTI_WE_WILL_ACCEPT_INS_CANCELATION,
	INS_MLTI_U_CAN_REST_ASSURED,
	INS_MLTI_HAD_U_HIRED_AN_INDIVIDUAL,
	INS_MLTI_WE_RESERVE_THE_RIGHT,
	INS_MLTI_SHOULD_THERE_BE_GROUNDS,
	INS_MLTI_SHOULD_SUCH_A_SITUATION,
	INS_MLTI_TO_PURCHASE_INSURANCE,
	INS_MLTI_ONCE_SATISFIED_CLICK_ACCEPT,
	INS_MLTI_SORRY_U_CANT_CANCEL,
	INS_MLTI_ARE_U_SURE_U_CANCEL,
	INS_MLTI_NO_QUALIFIED_MERCS,
	INS_MLTI_NOT_ENOUGH_FUNDS,
	INS_MLTI_ALL_AIM_MERCS_ON_SHORT_CONTRACT,
	INS_MLTI_1_HOUR_EXCLUSION_A,
	INS_MLTI_1_HOUR_EXCLUSION_B,

};

void OpenInsuranceTexts();
void CloseInsuranceTexts();
ST::string GetInsuranceText(const UINT8 ubNumber);
